// <auto-generated />
namespace Benefit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SellerOnlinePhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SellerOnlinePhone));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241024136_SellerOnlinePhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
