// <auto-generated />
namespace Benefit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCustomMarginSellerCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCustomMarginSellerCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201906122224446_AddCustomMarginSellerCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
