// <auto-generated />
namespace Benefit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDefaultProductImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDefaultProductImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202008200932212_AddDefaultProductImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
