// <auto-generated />
namespace Benefit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProductBarcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProductBarcode));
        
        string IMigrationMetadata.Id
        {
            get { return "202201100959454_AddProductBarcode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
